GET http://localhost:3000/login
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "titiwat.te06@gmail.com",
  "password": "Ty160760*"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "titiwat.te06@gmail.com",
  "password": "Ty160760*"
}